name: Test

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm-cache
      - name: Install Dependencies 🔧
        run: npm install --legacy-peer-deps

      - name: Build 🏗️
        run: npm run build

      - name: Upload Build Result 🚀
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: ./build
  publish-npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: DownLoad Dist
        uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: ./build
      - name: Publish To Npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.KNE_PACKAGE_PUBLISH}}
        run: npm publish --access=public

      - name: Sync To Cnpm
        run: npx cnpm sync packageName

  publish-gh-pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: DownLoad Dist
        uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: ./build
      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
  clean:
    runs-on: ubuntu-latest
    needs: [ 'publish-npm','publish-gh-pages' ]
    steps:
      - name: Clean Artifact
        uses: actions/delete-artifact@v4
        with:
          name: build-dist

