on:
  workflow_call:
    inputs:
      branch_name:
        type: string
jobs:
  complete-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "ISSUE_NUMBER=$(echo "${{ github.event.pull_request.head.ref }}" | sed 's/^issue-\([0-9]*\).*/\1/')"  >> "$GITHUB_ENV"
      - name: Check if ISSUE_NUMBER is a number
        id: check_number
        run: |
          str="${{ env.ISSUE_NUMBER }}";
          if [[ "$str" =~ ^[0-9]+$ ]]; then
            echo "::set-output name=is_number::true"
          else
            echo "::set-output name=is_number::false"
          fi
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ env.ISSUE_NUMBER }}
          comment: Auto-closing issue
      - name: Delete source branch
        if: steps.check_number.outputs.is_number == 'true'
        run: |
          BRANCH_NAME=$(echo "${{ inputs.branch_name || github.event.pull_request.head.ref }}" | tr '[:upper:]' '[:lower:]')
          git push origin --delete $BRANCH_NAME
