on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "VERSION=$(npx @kne/npm-tools latestVersion ${{inputs.package_name}} | tail -1)" >> "$GITHUB_ENV"
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{env.VERSION}}
