on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      artifact:
        required: false
        type: string
        default: build-dist
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: ${{inputs.artifact}}
          path: ./
      - name: Get version from package.json
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{env.VERSION}}
          skipIfReleaseExists: true
