on:
  workflow_call:
    inputs:
      APP_ID:
        required: true
        type: string
      TOKEN_SECRET:
        required: true
        type: string

jobs:
  miniprogram-qrcode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
      - run: npx @kne/miniprogram-tools qrcode
        env:
          APP_ID: ${{inputs.APP_ID}}
          SECRET: ${{secrets.TOKEN_SECRET}}
      - uses: kne-union/actions-deploy-static-data@master
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          name: ${{context.repository.name}}
