on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: ./
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
      - name: Publish Npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.KNE_PACKAGE_PUBLISH}}
        run: npm publish --access=public
      - name: Sync To Cnpm
        run: npx cnpm sync ${{inputs.package_name}}
