on:
  workflow_call:
    inputs:
      artifact:
        required: true
        type: string
        default:
          build-dist
      PROJECT_DIR:
        required: true
        type: string
        default: ./
      APP_ID:
        required: true
        type: string
      PRIVATE_KEY_NAME:
        required: true
        type: string
jobs:
  publish-miniprogram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact}}
          path: ./
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
      - run: npx @kne/miniprogram-tools
        env:
          PROJECT_DIR: ${{inputs.PROJECT_DIR}}
          APP_ID: ${{inputs.APP_ID}}
          PRIVATE_KEY: ${{ secrets[inputs.PRIVATE_KEY_NAME] }}

