on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: |
            ./
            !.git
            !${{ github.workspace }}/.husky
            !${{ github.workspace }}/.github
  publish-npm:
    needs: checkout
    uses: kne-union/actions/.github/workflows/publish-npm-workflow.yml@master
    secrets: inherit
    with:
      package_name: ${{inputs.package_name}}
  sync-static-data:
    runs-on: ubuntu-latest
    needs: publish-npm
    steps:
      - uses: kne-union/actions-manifest@master
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
  release:
    needs: publish-npm
    uses: kne-union/actions/.github/workflows/npm-release-workflow.yml@master
    secrets: inherit
    with:
      package_name: ${{inputs.package_name}}
