on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: ./
  publish-npm:
    needs: checkout
    uses: kne-union/actions/.github/workflows/publish-npm-workflow.yml@master
    secrets: inherit
    with:
      package_name: ${{inputs.package_name}}
  release:
    runs-on: ubuntu-latest
    needs: publish-npm
    steps:
      - run: echo "VERSION=$(npx @kne/npm-tools latestVersion ${{inputs.package_name}} | tail -1)" >> "$GITHUB_ENV"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: build-dist
          tag: ${{env.VERSION}}
  clean:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Clean Artifact
        uses: actions/delete-artifact@v4
        with:
          name: build-dist
