on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      example_package_name:
        required: true
        type: string
jobs:
  build-and-publish-lib:
    uses: kne-union/actions/.github/workflows/build-and-publish-lib-workflow.yml@master
    secrets: inherit
    with:
      package_name: ${{inputs.package_name}}
  build-and-publish--example:
    needs: build-and-publish-lib
    uses: kne-union/actions/.github/workflows/build-and-publish-example-workflow.yml@master
    secrets: inherit
    with:
      package_name: ${{inputs.example_package_name}}
  sync-static-data:
    runs-on: ubuntu-latest
    needs: build-and-publish--example
    steps:
      - uses: kne-union/actions-manifest@master
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
  sync-uc:
    runs-on: ubuntu-latest
    needs: sync-static-data
    timeout-minutes: 2
    continue-on-error: true
    steps:
      - name: Sync To UC
        run: |
          curl --header "Content-Type: application/json" --request POST --data "{\"PACKAGE_NAME\":\"${{inputs.example_package_name}}\"}" ${{secrets.SYNC_WEB_HOOK}}
  release:
    needs: build-and-publish-lib
    uses: kne-union/actions/.github/workflows/npm-release-workflow.yml@master
    secrets: inherit
    with:
      package_name: ${{inputs.package_name}}


