on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm i --legacy-peer-deps
      - run: npm run build

      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Auto Version
        run: npx @kne/npm-tools nextPatchVersion

      - uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: |
            ./build
            ./package.json
  publish-npm:
    needs: build-lib
    uses: kne-union/actions/.github/workflows/publish-npm-workflow.yml@master
    secrets: inherit

  release:
    needs: publish-npm
    uses: kne-union/actions/.github/workflows/npm-release-workflow.yml@master
    secrets: inherit
    with:
      package_name: ${{inputs.package_name}}


