on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      APP_ID:
        required: true
        type: string
      PRIVATE_KEY_NAME:
        required: true
        type: string
      TOKEN_SECRET_NAME:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm i --legacy-peer-deps
      - run: npm run init
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: |
            ./dist
            ./package.json
      - uses: actions/upload-artifact@v4
        with:
          name: example-dist
          path: |
            ./example/dist
            ./example/package.json
            ./example
  publish-miniprogram:
    needs: build
    uses: kne-union/actions/.github/workflows/publish-miniprogram-workflow.yml@master
    secrets: inherit
    with:
      PROJECT_DIR: ./example
      APP_ID: ${{inputs.APP_ID}}
      PRIVATE_KEY_NAME: ${{inputs.PRIVATE_KEY_NAME}}
  publish-npm:
    needs: build
    uses: kne-union/actions/.github/workflows/publish-npm-workflow.yml@master
    secrets: inherit
    with:
      package_name: ${{inputs.package_name}}
      artifact: example-dist
  publish-qrcode:
    needs: publish-miniprogram
    uses: kne-union/actions/.github/workflows/publish-miniprogram-qrcode.yml@master
    secrets: inherit
    with:
      APP_ID: ${{inputs.APP_ID}}
      TOKEN_SECRET_NAME: ${{inputs.TOKEN_SECRET_NAME}}
  release:
    needs: publish-npm
    uses: kne-union/actions/.github/workflows/npm-release-workflow.yml@master
    secrets: inherit
    with:
      package_name: ${{inputs.package_name}}


