on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      artifact:
        required: false
        type: string
        default: build-dist
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact}}
          path: ./
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
      - run: ls
      - name: Publish Npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.KNE_PACKAGE_PUBLISH}}
        run: npm publish --access=public
  sync-cnpm:
    runs-on: ubuntu-latest
    needs: publish
    timeout-minutes: 2
    continue-on-error: true
    steps:
      - name: Sync To Cnpm
        run: npx cnpm sync ${{inputs.package_name}}
