on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm i --legacy-peer-deps
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: |
            ./build
            ./package.json
  publish-npm:
    needs: build
    uses: kne-union/actions/.github/workflows/publish-npm-workflow.yml@master
    secrets: inherit
    with:
      package_name: ${{inputs.package_name}}
  sync-static-data:
    runs-on: ubuntu-latest
    needs: publish-npm
    steps:
      - uses: kne-union/actions-manifest@master
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
  sync-uc:
    runs-on: ubuntu-latest
    needs: sync-static-data
    timeout-minutes: 2
    continue-on-error: true
    steps:
      - name: Sync To UC
        run: |
          curl --header "Content-Type: application/json" --request POST --data "{}" ${{secrets.SYNC_WEB_HOOK}}
  release:
    needs: publish-npm
    uses: kne-union/actions/.github/workflows/npm-release-workflow.yml@master
    secrets: inherit
    with:
      package_name: ${{inputs.package_name}}


