name: Test

on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: kne-union/actions-manifest@master
        with:
          github_token: ${{ secrets.ADMIN_TOKEN }}
