name: Test

on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'kne-union/static-data'
          ref: 'master'
      - run: |
          rm -rf ./manifest && mkdir ./manifest
          npx @kne/npm-tools manifest
          cp -r ./build/* ./manifest
          rm -rf ./build
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'master'
          force: true
