name: Test

on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'master'
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          rm -rf ./manifest && mkdir ./manifest
          npx @kne/npm-tools manifest
          cp -r ./build/* ./manifest
          rm -rf ./build
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: 'master'
