name: Test

on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: kne-union/actions-deploy-static-data@master
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          name: test
